### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by mboeru** [mattjmcnaughton/fmc#2]
Hello,

I find your project really interesting, and I did not find any other that claims to do what this does, and is open source :).
I have tried to get it to work but without any luck unfortunately.

Is there any way you might be able to improve the docs or help me get it to run?

I am using OS X with the Docker for OSX, I start by running make, which seems to work, but when I run make run, it fails.

```
❯ make run
docker run -it --rm -v /Users/zen/repos/fmc:/fmc mattjmcnaughton/fmc-dev bash -c "PYTHONPATH='.' luigi --module fmc.tasks ExtractAllConversationLinks --local-scheduler --username mboeru --access-token XXXXXXXX"
Traceback (most recent call last):
  File "/usr/local/bin/luigi", line 9, in <module>
    load_entry_point('luigi==2.3.0', 'console_scripts', 'luigi')()
  File "/usr/local/lib/python3.5/site-packages/luigi/cmdline.py", line 11, in luigi_run
    run_with_retcodes(argv)
  File "/usr/local/lib/python3.5/site-packages/luigi/retcodes.py", line 69, in run_with_retcodes
    with luigi.cmdline_parser.CmdlineParser.global_instance(argv):
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/luigi/cmdline_parser.py", line 52, in global_instance
    new_value = CmdlineParser(cmdline_args)
  File "/usr/local/lib/python3.5/site-packages/luigi/cmdline_parser.py", line 76, in __init__
    Register.get_task_cls(root_task)
  File "/usr/local/lib/python3.5/site-packages/luigi/task_register.py", line 184, in get_task_cls
    raise TaskClassNotFoundException(cls._missing_task_msg(name))
luigi.task_register.TaskClassNotFoundException: No task ExtractAllConversationLinks. Candidates are: Config,ExternalTask,RangeBase,RangeDaily,RangeDailyBase,RangeHourly,RangeHourlyBase,Task,TestNotificationsTask,WrapperTask,core,execution_summary,retcode,scheduler,worker
make: *** [run] Error 1
```

Maybe I am doing something wrong?

Many thanks in advance!

**Comment by mattjmcnaughton** [comment]
Hi @mboeru - I must have missed your message - my apologies!

I posted the project while it was still a work in progress, but it should be working now. Although I'm not entirely sure that it is completely working in terms of how deep in the conversation history it is going (still have some final tweaks to make before production ready).

Let me know if that works!

**Comment by mboeru** [comment]
Hi Matt,

Sorry, I was on holiday last week.

I tried to run, but I am still getting an error. Might it be a wrong api key? Maybe I did not generate it where I should have.
```
❯ make run NAME='mboeru' ACCESS_TOKEN=XXXXXXXXX                                                                                                                                                      fmc/git/master 
docker run -it --rm -v /Users/zen/repos/fmc:/fmc mattjmcnaughton/fmc-dev bash -c "PYTHONPATH='.' luigi --module fmc.tasks ExtractMessages --local-scheduler --name 'mboeru' --access-token 'XXXXXXXXX'"
DEBUG: Checking if ExtractMessages(name=mboeru, access_token=XXXXXXXXX) is complete
DEBUG: Checking if ExtractPaginatedThreadEndpoints(name=mboeru, access_token=XXXXXXXXX) is complete
INFO: Informed scheduler that task   ExtractMessages_42b4711e13436161_mboeru_60cd70d466   has status   PENDING
DEBUG: Checking if ExtractThreadId(name=mboeru, access_token=XXXXXXXXX) is complete
INFO: Informed scheduler that task   ExtractPaginatedThreadEndpoints_42b4711e13436161_mboeru_60cd70d466   has status   PENDING
INFO: Informed scheduler that task   ExtractThreadId_42b4711e13436161_mboeru_60cd70d466   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 3
INFO: [pid 1] Worker Worker(salt=199909829, workers=1, host=0b813b79c066, username=root, pid=1) running   ExtractThreadId(name=mboeru, access_token=XXXXXXXXX)
ERROR: [pid 1] Worker Worker(salt=199909829, workers=1, host=0b813b79c066, username=root, pid=1) failed    ExtractThreadId(name=mboeru, access_token=XXXXXXXXX)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/luigi/worker.py", line 181, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/site-packages/luigi/worker.py", line 119, in _run_get_new_deps
    task_gen = self.task.run()
  File "/fmc/fmc/tasks.py", line 22, in run
    outfile.write(requester.get_thread_id())
  File "/fmc/fmc/lib/facebook.py", line 44, in get_thread_id
    for thread in resp_json['data']:
KeyError: 'data'
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Skipping error email. Set `error-email` in the `core` section of the Luigi config file or override `owner_email` in the task to receive error emails.
INFO: Informed scheduler that task   ExtractThreadId_42b4711e13436161_mboeru_60cd70d466   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 2 pending tasks possibly being run by other workers
DEBUG: There are 2 pending tasks unique to this worker
INFO: Worker Worker(salt=199909829, workers=1, host=0b813b79c066, username=root, pid=1) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 1 failed:
    - 1 ExtractThreadId(name=mboeru, access_token=XXXXXXXXX)
* 2 were left pending, among these:
    * 2 had failed dependencies:
        - 1 ExtractMessages(name=mboeru, access_token=XXXXXXXXX)
        - 1 ExtractPaginatedThreadEndpoints(name=mboeru, access_token=XXXXXXXXX)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====
```

**Comment by mattjmcnaughton** [comment]
No worries! Hmm - to be honest, the logging/error handling is not as good as it could be right now (my apologies - the project is still a work in progress). So it's a little difficult for me to tell. Would you mind including the contents of `resp_json`? Just include a `print(resp_json)` statement above line 44 in `fmc/fmc/lib/facebook.py`. Thanks!
